### ISSUE TITLE
P5: Naming inconsistencies

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#15]
When creating the scroll node, the code disagrees on what it should be called. It asks for this code:

var scrollNode: SKNode!

and then this:

scrollLayer = self.childNodeWithName("scrollLayer")

**Comment by cocojoe** [comment]
If in doubt, check the solution.  Tends to be copy/paste issues durning amends. Should be `var scrollNode: SKNode!`.
