### ISSUE TITLE
Next / Prev buttons in Online Academy 

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#18]
- Navigate to the bottom of a page (I was on Adding player controls - P5 of the bunny tutorial)
- press next page button
- navigate to the bottom of the new page
- press prev button

Navigates to the bottom of the previous page

- press next

Navigate to the bottom of the next page

**Comment by cocojoe** [comment]
@dionlarson web issues?
