### ISSUE TITLE
P7 Typos

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#19]
Under Physics Contact Delegate, the sentence "If the bunny collides with the ground, an obstacle or passes through the goal of an obstacle, you want to know about." - should probably have an 'it' at the end.

**Comment by zontan** [comment]
Under 'Game Over', another typo: "There is no easy way to add a button in SpriteKit so you will need to get creative and create our own solution." - changes from second to first person in the middle of a sentence. Should be you/your or we/our

**Comment by zontan** [comment]
And under Game State:  "just look intp"

**Comment by zontan** [comment]
And in the Bunny Death section, the code snippet stops being a code snippet halfway through, instead returning to plaintext.

**Comment by zontan** [comment]
Also, the tutorial uses lines like "buttonRestart.state = .MSButtonNodeStateHidden" and "buttonRestart.state = .MSButtonNodeStateActive" which should just use .Hidden and .Active, respectively.

**Comment by zontan** [comment]
Slightly below the plaintext code: "removing the flapping asprite"

**Comment by zontan** [comment]
In Shutting Down The World: "bunny will still respond every so slightly"

**Comment by cocojoe** [comment]
@zontan you have my blessing to make a pull request after you've completed your review. This would be most helpful, thanks.

**Comment by zontan** [comment]
And finally in Summary: "Implementing the SKPhysicsContactDelegate so you are informed of collision conacts." =)

**Comment by zontan** [comment]
@cocojoe I've updated all the easy typo things, but I'm not sure what's wrong with the code snippet formatting because I'm not 100% sure how that formatting works.
