### ISSUE TITLE
Problem with obstacles

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#2]
I was building this project. and get the following error: 

removing obstacle
2016-04-23 17:30:49.954 HoppyBunny[3159:255103] *** Terminating app due to uncaught exception 'Cant add body, already exists in a world', reason: 'Cant add body <SKPhysicsBody> type:<Rectangle> representedObject:[<SKScene> name:'(null)' frame:{{-25.5, -384}, {51, 768}} anchor:{0.5, 0.5}], already exists in a world'

Of course the error could be mine.

**Comment by cocojoe** [comment]
The is a **runtime** issue related to the **adding** of the obstacle in the following code:

```
let newObstacle = SKReferenceNode.init(fileNamed: "Obstacle") as SKReferenceNode!
obstacleLayer.addChild(newObstacle)
```

This appears to be an Xcode 7.3+ issue, this runs perfectly in Xcode 7.2.1.  I've asked on Apple Forum and filled a bug report.

https://forums.developer.apple.com/message/128402

**Comment by soggybag** [comment]
What seemed to work for me was to use skNode.copy() instead of SKReferenceNode(). This required that the original obstacle be saved off screen and used as a source to create copies. 

I'll update my fork when I finish working through the rest of the tutorial.

**Comment by cocojoe** [comment]
This is a valid option, one I'm sure you noticed was used in Sushi Neko.  For Hoppy Bunny the first obstacle is already in the scene anyway.  Create your pull when ready and I'll review.  Thx

**Comment by cocojoe** [comment]
Thanks for the alternative option, I did some digging and found a workaround for loading in Xcode 7.3 so will be using that now.

```
let resourcePath = NSBundle.mainBundle().pathForResource("Obstacle", ofType: "sks")
let newObstacle = SKReferenceNode (URL: NSURL (fileURLWithPath: resourcePath!))
obstacleLayer.addChild(newObstacle)
```
