### ISSUE TITLE
P6 Missing the code that calls method scrollWorld()

### ISSUE THREAD

**Issue by AnnMic** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#20]
In the section Scroll World It says "Then add the following to the bottom of your update(...) method:
" 

but the box were the code should be displayed is empty. Should include scrollWorld()

**Comment by dionlarson** [comment]
Fixed in 75d75e7. The code was there but the renderer was having issues with the way it was formatted...
