### ISSUE TITLE
Bunny Death Formatting

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#22]
It appears that the code formatting is broken for Bunny Death

**Comment by cocojoe** [comment]
Can you be more specific please, line #? Please include a screenshot of the rendering.  Thx

**Comment by esscbee** [comment]
<img width="1072" alt="screen shot 2016-06-10 at 1 40 46 pm" src="https://cloud.githubusercontent.com/assets/8846585/15978092/018c930c-2f11-11e6-9941-66802e8f5ebf.png">
