### ISSUE TITLE
Hide the Button

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#23]
The line of code reads:

  buttonRestart.state = .MSButtonNodeStateHidden

It should read

  buttonRestart.state = .Hidden

**Comment by esscbee** [comment]
Similar for the code in didBeginContact.  It should be .Active.

**Comment by cocojoe** [comment]
The code was updated but not the documentation, please create a pull request and amend usage.  Thx
