### ISSUE TITLE
P4 - Can't click and download file

### ISSUE THREAD

**Issue by davichaves** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#29]
<img width="1102" alt="screen shot 2016-06-10 at 4 54 16 pm" src="https://cloud.githubusercontent.com/assets/7053287/15981599/2ecd390a-2f2c-11e6-9ba1-e887b2172ddc.png">

**Comment by AnnMic** [comment]
This should had been fixed in a closed issue, try to refresh the page

**Comment by dionlarson** [comment]
Fixed for real in fc6912f4eda809e1dd1a5098a1879a8dcd90a862
