### ISSUE TITLE
P4:  Z Position: Issues regarding sibling order

### ISSUE THREAD

**Issue by szilardinho** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#30]
Remind students that objects will NOT render in the proper order even if the zPositions are explicitly set if in the GameViewController.swift file the ignoresSiblingOrder is set to true.

So this,
skView.ignoresSiblingOrder = true 

should be this,
skView.ignoresSiblingOrder = false

I completely forgot this option in SpriteKit and was confused for a while why my nodes were all over the place when I set their zPositions in the InterfaceBuilder's GameScene.sks file, then I even set them programmatically in the GameScene.swift file to no avail so this was definitely helpful if anyone is experiencing the same problems.

**Comment by dionlarson** [comment]
Can you post screenshots of the messed up z-order and include z-order values for each sprite on the screen? It's likely you did not set them up correctly (very well might be the tutorial's fault).

> When this property is set to true, the position of the nodes in the tree is ignored when determining the rendering order. The rendering order of nodes at the same z position is arbitrary and may change every time a new frame is rendered. When sibling and parent order is ignored, SpriteKit applies additional optimizations to improve rendering performance. If you need nodes to be rendered in a specific and deterministic order, you must set the z position of those nodes.
