### ISSUE TITLE
Holding down shift does not snap

### ISSUE THREAD

**Issue by thefreshduke** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#38]
In "3. Set up the Game Scene", under "Add the background", we are told that holding down shift allows us to snap objects. Holding down shift actually cancels snap, so we should simply drag if we want to snap

**Comment by cocojoe** [comment]
This can be removed @zontan , originally designed in Xcode 7.2 and the default behaviour was you needed to hold shift for snapping.  In 7.3 they switched the behaviour.

**Comment by zontan** [comment]
@cocojoe Do we still want to tell them about holding down shift to disable snapping, or just remove the info section entirely?

**Comment by cocojoe** [comment]
Hmm yeah that's a good point, I'll mention disabling.
