### ISSUE TITLE
2. Basic concepts of a side scroller

### ISSUE THREAD

**Issue by StanfordLin** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#46]
Adding Sound Effects 

When dragging the SFX folder into XCode, it would better if "Create Groups" could be clarified.

![screen shot 2016-07-06 at 2 30 43 pm](https://cloud.githubusercontent.com/assets/16379094/16635248/5fbe42ca-4386-11e6-81b7-a6b97ef0dea9.png)

**Comment by djh-** [comment]
Fixed in 01654dbbe591c391da8d616190f82ae2dbe72eef
