### ISSUE TITLE
P4 use of CCTime

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift#9]
CCTime is a Cocos2d class, which we are not using. We are told to use it to track time since last click, which totally doesn't work.

**Comment by esscbee** [comment]
Should this be CFTime?

**Comment by esscbee** [comment]
looks like changing this line to:

    var sinceTouch = 0.0

gets you past this

**Comment by dionlarson** [comment]
`CFTimeInterval` is the correct type
